# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/SourcesForOlympCirclesBd/Basys3Master.xdc

# Block Designs: bd/olymp/olymp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==olymp || ORIG_REF_NAME==olymp} -quiet] -quiet

# IP: bd/olymp/ip/olymp_ckVideoGen_0_0/olymp_ckVideoGen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==olymp_ckVideoGen_0_0 || ORIG_REF_NAME==olymp_ckVideoGen_0_0} -quiet] -quiet

# IP: bd/olymp/ip/olymp_ctrlImgOlymp_0_0/olymp_ctrlImgOlymp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==olymp_ctrlImgOlymp_0_0 || ORIG_REF_NAME==olymp_ctrlImgOlymp_0_0} -quiet] -quiet

# IP: bd/olymp/ip/olymp_imgCombOlymp_0_0/olymp_imgCombOlymp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==olymp_imgCombOlymp_0_0 || ORIG_REF_NAME==olymp_imgCombOlymp_0_0} -quiet] -quiet

# IP: bd/olymp/ip/olymp_vgaCtrl_0_0/olymp_vgaCtrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==olymp_vgaCtrl_0_0 || ORIG_REF_NAME==olymp_vgaCtrl_0_0} -quiet] -quiet

# XDC: bd/olymp/olymp_ooc.xdc
